---
- hosts: all
  vars:
    samara: '~'
  tasks:
    - file:
        path: '{{ samara }}/beatiful'
        state: touch
  when:  ansible_facts['distribution'] == "CentOS"
    - file:
        path: '{{ samara }}/daisy'
        state: directory
  when:  ansible_facts['distribution'] == "Ubuntu"
   
       
     
    

