---
- hosts: all
  vars:
    myprograms:
      - httpd
      - wget
      - ntp
      - tree
    myfolders:
      - til
      - bash
      - murun
      - kulak
      - kursak
  tasks:
    - yum: 
        name: "{{ myprograms }}"
        state: latest
    - file:
        name: ~/"{{ myfolders }}"
        state: directory
  