---
- hosts: web
  vars:
    myshort: '/tmp'
  tasks:
    - file:
        path: '{{ myshort }}/flower'
        state: directory   
      when:  ansible_facts['distribution'] == "CentOS"
    - file:
        path: '{{ myshort }}/tulip'
        state: directory
      when:  ansible_facts['distribution'] == "Ubuntu"     
