---
- hosts: web
  vars:
    myshort: '/tmp'
  tasks:
    - file:
        path: '{{ myshort }} flower'
        state: touch   
    - file:
        path: '{{ myshort }} /tmp/tulip'
        state: directory
      when:  ansible_facts['distribution'] == "Ubuntu"     
