---
- hosts: web
  vars:
    my_uzun: '~'
  tasks:
    - file: 
        path: '{{ my_uzun }}/treefile'
        state: touch
    - file:
        path: '{{ my_uzun }}/samarafolder'
        state: directory
      when: ansible_facts['distribution'] == "Ubuntu"