---
- hosts: all
  tasks:
    - yum:
        name: httpd
        state: latest
    - file:
        path: /tmp/return.yml
        state: touch 
    - file:
        path: ~/myfolder10
        state: directory

