---
- hosts: web
  vars:
    packs:
      - httpd
      - wget
      - ntp
  tasks:
    - name: Installing packages
      yum:
        name: "{{ packs }}" 
        state: latest
        lock_timeout: 180