---
- hosts: web
  tasks:
    - yum:
        name: httpd
        state: latest
    - file:
        path: /etc/myfolder.yml
        state: touch     
    - file:
        path: /var/kukla.yml
        state: directory
        
      
      